import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import connect from "@/lib/mongodb";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  connect();

  return (
    <html lang="en">
      <body className={`${inter.className} grid grid-rows-[auto_1fr_auto] min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
